### ISSUE TITLE
Are there any performance comparison Wiltondb has against SQL server ?

### ISSUE THREAD

**Issue by psrinivasa2** [wiltondb/wiltondb#21]
Need to understand the performance angles of WiltonDB, Does the performance testing has already been done for WIltonDB against the SQL server and Is the any report for the same?

**Comment by psrinivasa2** [comment]
Hi @staticlibs ,
Thanks for the detail. Curious to know is there any performance report you have taken for WiltonDB vs PostgreSQL and  WiltonDB vs SQL Server?

**Comment by staticlibs** [comment]
No, sorry, don't have benchmarking results, running a [TPC-C](https://www.tpc.org/tpcc/) benchmark properly requires non-trivial amount of effort.

**Comment by psrinivasa2** [comment]
understood @staticlibs,  Is it something on your pipeline to check later?

**Comment by staticlibs** [comment]
No, no synthetic benchmarks are planned, IMO amount of effort required does not worth it.

**Comment by bill-ramos-rmoswi** [comment]
Hi @psrinivasa2 , only you can perform this benchmark in the environment you expect to use as your production environment. Take a look at https://aws.amazon.com/blogs/modernizing-with-aws/comparing-performance-of-new-releases-of-babelfish-and-comparing-babelfish-performance-with-sql-server/ for what is possible. Keep in mind the HammerDB TPCC workload may be nothing like your environment. The reason that Babelfish did well against SQL Server price/performance is that on EC2, the IOPS got throttled based on the instance size. That same instance running on Aurora PostgreSQL or Aurora PostgreSQL with Bbaelfish doesn't get throttled. As a result, this benchmark ends up limiting EC2 performance because the bottleneck is IOPS and not memory, CPU, or network bandwidth. On Aurora, especially with the new IO-Optimized storage, the benchmark gets limited by CPU because it's processing transactions so much faster.

If you are running WiltonDB on-premises you won't experience the IOPS throttling effect. If you are using HDD based storage, your bottleneck will be storage. If it's HDD with the latest NVMe drives, your bottleneck with the TPCC benchmark will be CPU. If you run TPCH which has "analytic" queries, your bottleneck can shift to local memory on the server.

You can follow Alex's steps in the blog - https://aws.amazon.com/blogs/modernizing-with-aws/using-hammerdb-for-babelfish-performance-testing/ to test for yourself in your environment. HammerDB includes a PostgreSQL option, but it is tricky to set it up on a Windows server.

But, it's all about your application! Figure out how you can load test your application based on the customer usage and known scalability issues you might have with SQL Server today. I recommend instrumenting your application and application calls with open-telemetry - https://opentelemetry.io/docs/languages/net/getting-started/.

Another thing to understand is that things that work ok in SQL Server may run poorly against PostgreSQL and Babelfish. This is because of common anti-patterns used with T-SQL can magnify by 2 to 1000 times with the PostgreSQL engine. An example is correlated sub-queries. The SQL Server team invested a lot of time to address this issue, but no one in the PostgreSQL community addressed the issue. For now, you need to work around the problem using a technique described here - https://alibaba-cloud.medium.com/query-optimization-technology-for-correlated-subqueries-8d265a51f58e.

There are many others that can make your application run sloooow. 

One way you can examine your code is to use the Claude LLM - you can do this for free. Try this against your T-SQL code and you will get an idea of what your are up against.

### Anti-pattern analysis using https://claude.ai/new
Prompt:
Please identify the T-SQL anti-patterns in the following code which could cause performance or 
reliability issues  (too many locks or blocks on other queries). In the summary intended for a 
SQL Server DBA with 10 years of experience includes the name of the anti-pattern, an example 
from the code, and the potential solution to fix the pattern. Also, include reference links for the 
DBA to learn more.

Example response you can get:
Thank you for providing the code. I'll analyze it for T-SQL anti-patterns that could cause performance 
or reliability issues, particularly focusing on excessive locking or blocking. Here's a summary tailored 
for a SQL Server DBA with 10 years of experience:

1. Anti-pattern: Large-scale Data Modifications
Example: The entire procedure is performing large-scale data modifications across multiple tables.
Potential solution: Consider breaking this into smaller, more focused stored procedures and use batching for large updates.
Reference: https://www.sqlshack.com/how-to-handle-large-data-sets-in-sql-server/

2. Anti-pattern: Excessive Use of Table Variables
Example: Multiple table variables are declared and used throughout the procedure.
Potential solution: For large datasets, consider using temporary tables instead, as they can be more efficient and have better statistics.
Reference: https://www.brentozar.com/archive/2014/08/table-variables-good-temp-tables-bad-or-other-way-around/

3. Anti-pattern: Lack of SET XACT_ABORT ON
Example: The procedure doesn't use SET XACT_ABORT ON.
Potential solution: Add SET XACT_ABORT ON at the beginning of the procedure to ensure consistent error handling and transaction management.
Reference: https://learn.microsoft.com/en-us/sql/t-sql/statements/set-xact-abort-transact-sql

4. Anti-pattern: Using CHANGETABLE without explicit versioning control
Example: CHANGETABLE(CHANGES [dbo].[FlatStore], @Version) is used multiple times.
Potential solution: Implement explicit version control to ensure consistent change tracking across multiple tables.
Reference: https://learn.microsoft.com/en-us/sql/relational-databases/track-changes/about-change-tracking-sql-server

5. Anti-pattern: Complex JSON Parsing in SQL
Example: Multiple instances of OPENJSON and JSON manipulation.
Potential solution: Consider moving complex JSON operations to the application layer where possible.
Reference: https://www.sqlshack.com/how-to-parse-json-in-sql-server/

6. Anti-pattern: Lack of Error Handling
Example: The procedure lacks comprehensive error handling.
Potential solution: Implement TRY...CATCH blocks and proper error logging throughout the procedure.
Reference: https://learn.microsoft.com/en-us/sql/t-sql/language-elements/try-catch-transact-sql

7. Anti-pattern: Potential Long-Running Transactions
Example: The entire procedure appears to run in a single transaction.
Potential solution: Consider breaking the operation into smaller, more manageable transactions where appropriate.
Reference: https://www.sqlshack.com/understanding-and-handling-blocking-in-sql-server/

8. Anti-pattern: Scalar User-Defined Functions in SELECT Statements
Example: Several UDFs are used in SELECT statements, like dbo.GetStateNameByCode.
Potential solution: Consider inlining these functions or replacing them with more efficient set-based operations.
Reference: https://www.brentozar.com/archive/2015/10/the-problem-with-scalar-user-defined-functions/

**Comment by staticlibs** [comment]
In addition to @bill-ramos-rmoswi comment, if you are moving to Babelfish from MSSQL Express, for performance comparison you also need to take into account Express edition restrictions - only 4 cores, max 1410 MB buffer pool etc. Babelfish obviously does not have these restrictions.
