### ISSUE TITLE
WiltonDB Transfer GUI Tool (wdb_transfer) Issues

### ISSUE THREAD

**Issue by psrinivasa2** [wiltondb/wiltondb#23]
@staticlibs Facing below issues in WiltonDB transfer GUI tool (wdb_transfer). Could you please help us?

1) During the transfer of data's using the tool, getting the below issue,
Error = [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]duplicate key value violates unique constraint "babelfish_view_def_pkey"

This was already been discussed sometimes back [here](https://github.com/babelfish-for-postgresql/babelfish-for-postgresql/discussions/15#discussioncomment-9690215), but I would like to convey you that this happens for a table and when re-trigger migration for the same issue table, it gets succeeded again. This occurs for a average of 100 tables, one table gets issue and data migration stopped. Can you share your view on this?

2) Data migration was not fully complete, For example a employee table in sql server had 248 records, but the transfer tool migrated only 213 records, not sure why rest of 35 records not transferred. any idea on it?

3) Important Question - IDENTITY column not works in expected form in babelfish or postgreSQL after data migration. For example employeeId in employee table is identity column, the sql server had 100 records where the last identity sequence value is 100. After migration to postgreSQL, when trying to insert record to employee table, it not starts with 101 sequence, rather it was different like around 20. This is more important because we wanted to transfer the data and start sequence on top of it. Is there a way to fix this issue?

**Comment by staticlibs** [comment]
@psrinivasa2 

About `babelfish_view_def_pkey`: I didn't find any easy way to reproduce it ([details](https://github.com/babelfish-for-postgresql/babelfish-for-postgresql/discussions/15#discussioncomment-9700531)), really need some kind of reproducer to debug it. If you will be able to narrow the problem down to particular tables/records/constraints - it would be helpful.

About incomplete migration: 

1. `wdb_transfer` invokes bcp separately for every exported table. Each bcp run opens a new TDS connection and closes it after the table data is imported. So a backend Postgres process is started and stopped for each table. Thus the possibility of an in-memory corruption (due to some kind of bug in bulkload code) during import of one table that can affect the import of subsequent tables is virtually nil. So the problems must lie either in the data of the table being imported or in the on-disk data of related tables that are already imported.

2. I regularly use `wdb_transfer` on 2 - 5 GB DB with a few hundred tables, I haven't seen a single problem with it. What is specific about this DB is that it has very few constraints and do not use foreign keys at all. Can you please confirm if you are running the import with constraints/foreign keys enabled? Can you try the import after disabling constraints/foreign keys (with [something like this](https://stackoverflow.com/a/14973117)). Experimenting with constrains and bcp import I found problems with them (incorrect behaviour when constraint violation is found). There was a [recent upstream patch](https://github.com/babelfish-for-postgresql/babelfish_extensions/pull/2629) that disables constraints checks by default. This looks like a desired behaviour and I intend to backport this into next WiltonDB update (second part of the patch about "fix error aborting cycle" is already there, was implemented separately).

3. If you can narrow the problem to a minimal number of tables (by importing only selected tables in `wdb_transfer` UI) and then if these tables can be anonymized and shared as a reproducible example - this would be really helpful. After previous bcp investigations (done for `7.12` update) I feel well-versed with bulkload code - should be easy to debug.

About the identity column: I assume detailed explanation from @bill-ramos-rmoswi covers it.

**Comment by psrinivasa2** [comment]
@staticlibs kindly ignore the second issue, It was my mistake, I referred wrong zip file. Its works fine.
![image](https://github.com/wiltondb/wiltondb/assets/89133439/8ba97e6d-801b-4a5a-92fd-db697f146a7e)

**Comment by psrinivasa2** [comment]
Hi Alex @staticlibs,
Constraints checking is off by default in 11.15.1 - what is the config and where to check it? 

when I tried now in the same release still the same issue 'duplicate key value violates unique constraint "babelfish_view_def_pkey"' exists.

![image](https://github.com/user-attachments/assets/343bd899-2e93-445b-aa2a-1359215c7b9c)

**Comment by psrinivasa2** [comment]
![image](https://github.com/user-attachments/assets/ca78986e-917e-4d3a-a005-64d216c354dd)

**Comment by psrinivasa2** [comment]
Meanwhile let me try look at log file with suggested debug installer

**Comment by psrinivasa2** [comment]
Hi Alex (@staticlibs),
Shared you the log file details in the mail, please check it.

**Comment by staticlibs** [comment]
@psrinivasa2 

> Constraints checking is off by default in 11.15.1 - what is the config and where to check it?

Constraints check for BCP import can be enabled using [CHECK_CONSTRAINTS hint](https://learn.microsoft.com/en-us/sql/tools/bcp-utility?view=sql-server-ver16&tabs=linux#-h-hints---n), like this:

```
bcp ... -h"CHECK_CONSTRAINTS"
```

> Shared you the log file details in the mail, please check it.

Thanks for the log file! This is a problematic backtrace:

```
```

**Comment by staticlibs** [comment]
@psrinivasa2 , the error happens because of the name clash in temporary view name that is created in `sp_describe_first_result_set` (`22690` there is a random number):

```
ERROR:  duplicate key value violates unique constraint "babelfish_view_def_pkey"
DETAIL:  Key (dbid, schema_name, object_name)=(73, dbo, sp_describe_first_result_set_view_22690) already exists.
```

It is not clear to me why the name clash causes the error, because the view is short-lived, it is created and then dropped before every bulk import, thus subsequent BCP invocations should not see it (`wdb_transfer` does not run BCP in parallel). Though it happens for some reason in your environment.

As a workaround, I've changed the view suffix to UUID, so there should be no more clashes, please try to run the same import on [11-16-0-rc1 version](https://github.com/wiltondb/wiltondb/releases/tag/3.3-11-16-0-rc1).

**Comment by psrinivasa2** [comment]
Hi Alex @staticlibs,
Thanks much, the issue has been fixed now, migration is successful without any errors
