### ISSUE TITLE
Strange Issue -   Exists and Not Exists statements not works as expected

### ISSUE THREAD

**Issue by psrinivasa2** [wiltondb/wiltondb#28]
Strange Issue -   Exists and Not Exists statements not works as expected, please find below attached screenshots

![image](https://github.com/user-attachments/assets/8455866d-4892-42b3-94b4-a3465c0e7431)

![image](https://github.com/user-attachments/assets/3b8e1cf5-0aff-4792-b02f-846ca0687760)

IF NOT EXISTS( SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'dbo' AND  TABLE_NAME = 'DatabaseVersionHistory' AND  COLUMN_NAME = 'Patch')
BEGIN
	print 'Reached Not Exists condition'
END
else 
begin
	print 'Reached Exists condition'
end

**Comment by staticlibs** [comment]
This is indeed a bug with `INFORMATION_SCHEMA` views in T-SQL mode. Not directly related to `EXISTS`.

With the following table:

```tsql
CREATE TABLE DatabaseVersionHistory(Patch varchar(max))
```

Plain SQL uses correct undecorated T-SQL schema name:

```tsql
SELECT count(*) FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'dbo'
AND TABLE_NAME = 'DatabaseVersionHistory'
AND COLUMN_NAME = 'Patch'
```
```
count
-----------
1
```

T-SQL block requires Postgres-level real schema name and is case-sensitive for some reason (I suppose it looks into Postgres-native `INFORMATION_SCHEMA.COLUMNS` view instead of T-SQL one by mistake):

```tsql
DECLARE @num int = (
    SELECT count(*) FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_SCHEMA = 'dbo'
    AND TABLE_NAME = 'DatabaseVersionHistory'
    AND COLUMN_NAME = 'Patch')
SELECT @num
```
```
@num
-----------
0
```

```tsql
DECLARE @num int = (
    SELECT count(*) FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_SCHEMA = db_name() + '_' + 'dbo'
    AND TABLE_NAME = LOWER('DatabaseVersionHistory')
    AND COLUMN_NAME = LOWER('Patch'))
SELECT @num
```
```
@num
-----------
1
```

The problem seems to be limited to inline T-SQL blocks, the following function works correctly for me:

```tsql
CREATE FUNCTION dbo.ColumnExists(@schemaName varchar(63), @tableName varchar(63), @columnName varchar(63))
RETURNS varchar(1) AS
BEGIN
    DECLARE @result varchar(1)
    IF EXISTS (SELECT * FROM information_schema.columns WHERE table_schema = @schemaName AND table_name = @tableName AND column_name = @columnName)
    BEGIN
        SET @result = 'T'
    END ELSE
    BEGIN
        SET @result = 'F'
    END
    RETURN @result
END
```
```tsql
SELECT dbo.ColumnExists('dbo', 'DatabaseVersionHistory', 'Patch')
```
```
columnexists
------------
T
```

I will follow-up on this, I suggest to use a function for such queries as a workaround.

Also note, such `EXISTS` queries can hit another problem if overly long column/index/constraint names are used. There is an inherent limitation in Postgres that names must not exceed 63 bytes. Babelfish uses name mangling for longer names and this mangling should be taken into account in `EXISTS` checks. I can elaborate on this if necessary, see overview on [Long identifiers](https://github.com/babelfish-for-postgresql/babelfish-for-postgresql/wiki/Long-identifiers) wiki page.

**Comment by staticlibs** [comment]
There is actually a better workaround for this, `INFORMATION_SCHEMA_TSQL` (that is supposed to be picked up automatically) can be used directly in queries instead of `INFORMATION_SCHEMA`. With it initial problematic T-SQL block works correctly:

```tsql
```

**Comment by staticlibs** [comment]
Confirming that this problem is fixed in upstream Babelfish in [#1831](https://github.com/babelfish-for-postgresql/babelfish_extensions/pull/1831). Going to backport it and include into upcoming update that is planned for Monday.

**Comment by staticlibs** [comment]
@psrinivasa2 , here is the updated installer with this issue and #24 fixes included - [11.15.1 release page](https://github.com/wiltondb/wiltondb/releases/tag/3.3-11-15-1). Public announcement (readme update) for this release is still pending on Linux builds (that are currently blocked by ARM64 builds on Ubuntu public builder). But Windows MSI is ready to use.

**Comment by psrinivasa2** [comment]
Thanks Alex @staticlibs , I will do check the issues

**Comment by psrinivasa2** [comment]
the reported two issues has been tested and works fine, thanks much Alex, @staticlibs. This can be closed
