### ISSUE TITLE
Question: How to avoid the manual work in updating SSMS generated schema for bablefish issue fix changes for multiple branches of same project

### ISSUE THREAD

**Issue by psrinivasa2** [wiltondb/wiltondb#30]
Hi Alex @staticlibs,
We are currently following below steps for upgrade,

Generate the database schema from source database in SSMS generate scripts option, and the alter schema manually to remove out unneeded scripts and updating tables, function's, view's and stored procedure's manually to fix babelfish issues. Then execute the updated schema in babelfish connection string to create the database and schema in pstgreSQL.

The point is source database can be dev, main, anything else.  Every time we can't manually edit the schema file and append babelfish fix changes, since there are chances for human error to miss any fix. 

Is there any automatic process you are following where process can take the input as SSMS generated schema and gives us the output as babelfish issue fixed schema? In the automatic process we can still write the babelfish issues fix changes.

**Comment by bill-ramos-rmoswi** [comment]
Hi @psrinivasa2 , I'm working on a set of guidelines over the next week that address this issue. What tools are you using today to manage your DevOps pipeline with SQL Server code changes? I can take this into consideration as I put the guidelines into place.

BTW, I recommend getting a Claude.AI Pro subscription to assist your effort. You can use Claude.AI to address many of your concerns, including this one. It's all in the Prompt instructions feature with Claude projects.

For example, in my blog post https://medium.com/@rmoswi/so-long-and-thanks-for-all-the-strings-mastering-string-agg-53dd683b562a, I used Claude to help write and test the code for this article. When I get the desired result, I ask Claude to generate an Instruction that I can use to add to the Project's instruction set.
Thanks,
Bill

**Comment by bill-ramos-rmoswi** [comment]
Check out this YouTube video:
[Claude’s AMAZING ‘Custom Instructions’ Feature! (Full Guide)](https://www.youtube.com/watch?v=hP1bNevQEGI)

This changed the way that I do anything with SQL code forever! Part of the related project I'm working on is to create a model Claude.ai project for workarounds and optimization of T-SQL for Babelfish that's I'll post in the https://github.com/bill-ramos-rmoswi/babelfish_postgresql_towel repo,

**Comment by psrinivasa2** [comment]
Hi Bill,
Unfortunately my organization has blocked all the AI tools including above mentioned Claude.AI too.  

I was expecting something like a PowerShell scripts where I can write update, remove and insert scripts or any other simple equivalent

**Comment by staticlibs** [comment]
@psrinivasa2 , ideally you need to move the "source of truth" DDL out from MSSQL to not rely on SSMS schema export. For example to do schema export once, split the schema SQL into the number of SQL files and add a PowerShell (or Python/C# etc) script that needs to be run to create the schema in a clean DB. This script should check the DBMS name on startup and then to execute appropriate SQL files including/excluding Babelfish specific bits as necessary. And all subsequent schema changes should go through these SQL files before being applied to MSSQL. Schema update logic ("if exists" checks) also can be incorporated into such script. This effectively implements a [schema migration tool](https://en.wikipedia.org/wiki/Schema_migration) for your app.

If it is not possible to move "source of truth" DDL out from MSSQL (because of organizational reasons) and SSMS schema export is required, then the script described above is going to be Babelfish specific. It needs to take SSMS-exported SQL as as input and modify/decorate it as necessary before executing it in Babelfish. Because the schema is going to be more or less the same, I think you can get away with regular expression matching and string manipulation to split/extract/modify the SQL without doing the actual parsing. Full SQL parsing is also possible from such script, though in this case C# or Java may be more convenient to include ANTLR parser there like Babelfsh Compass is doing. If you also need to automate the step of exporting data from MSSQL (to do it from script, not from MSSQL), there is [sqltoolsservice](https://github.com/microsoft/sqltoolsservice) for this, though I don't have first hand experience with its usage.

**Comment by psrinivasa2** [comment]
Thanks Alex, I will do try out the suggestions
