### ISSUE TITLE
Not able to connect to SQL Server named instance in wdb_transfer tool for exporting the data from SQL side

### ISSUE THREAD

**Issue by psrinivasa2** [wiltondb/wiltondb#43]
Not able to connect to SQL Server named instance in wdb_transfer tool for exporting the data from SQL side

![image](https://github.com/user-attachments/assets/cea655b7-4809-427a-b335-d0bef027ba12)

**Comment by staticlibs** [comment]
@psrinivasa2 

This looks like a networking problem, two network endpoints are used when connecting to a named MSSQL instance:

1. UDP access to SQL Browser service on port 1434 to get the TCP port number of the corresponding instance

3. TCP access to SQL server instance on the port number fetched on step 1

To troubleshoot this, lets check the SQL Browser first, can you run this python script specifying the hostname as an argument:

```python
# -*- coding: utf-8 -*-
import socket
import sys

def send(host):
    addr = socket.gethostbyname(host)
    print("Checking MSSQL dynamic TCP support for address: [%s] ..." % addr)
    sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    sock.sendto(bytearray([2]), (addr, 1434))
    data, addr = sock.recvfrom(1024)
    print("MSSQL dynamic TCP data received: [%s] from addr: [%s]" % (data, addr))
    sock.close()

if __name__ == "__main__":
    if 2 != len(sys.argv):
        print("Please specify MSSQL hostname as a first and only argument")
    else:
        host = sys.argv[1]
        send(host)
```

Expected output when SQL Browser service is available:

```
> python sql_browser_test.py DESKTOP-JS80C9O
Checking MSSQL dynamic TCP support for address: [192.168.178.57] ...
MSSQL dynamic TCP data received: [b'\x05`\x00ServerName;DESKTOP-JS80C9O;InstanceName;SQLEXPRESS;IsClustered;No;Version;16.0.1000.6;tcp;6433;;'] from addr: [('192.168.178.57', 1434)]
```

When SQL Browser is not available:

```
> python sql_browser_test.py DESKTOP-JS80C9O                                                         
Checking MSSQL dynamic TCP support for address: [192.168.178.57] ...                                 
Traceback (most recent call last):                                                                   
  File "C:\tmp\sql_browser_test.py", line 19, in <module>                                        
    send(host)                                                                                       
  File "C:\tmp\sql_browser_test.py", line 10, in send                                            
    data, addr = sock.recvfrom(1024)                                                                 
                 ^^^^^^^^^^^^^^^^^^^                                                                 
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host 
```

**Comment by psrinivasa2** [comment]
Hi Alex @staticlibs ,
 I noticed that SQL Browser was disabled in my machine, then I started it and tried again. This time fails with different error
 
 
![image](https://github.com/user-attachments/assets/96d8310b-fea0-49d9-84e4-23c71f0d90f6)

**Comment by psrinivasa2** [comment]
After I assign particular PORT for named instance and try to connect via port, it works fine

![image](https://github.com/user-attachments/assets/e1566528-3acd-4f35-b6e7-64cb0b89bf79)

**Comment by staticlibs** [comment]
@psrinivasa2 

Can you share the output of the python script posted above? From the error message on the last screenshot I can guess that the response was received from SQLBrowser and the error happens when that response is processed in TDS client lib. The script will print this response, that should contain a list of `instance name` -> `TCP port` pairs (in binary form).

**Comment by psrinivasa2** [comment]
![image](https://github.com/user-attachments/assets/f0351001-8a85-4170-b093-e979e4f5a0d6)

**Comment by staticlibs** [comment]
Thanks for details! I cannot see anything unusual in this response. Need to look deeper to get why it can cause an error on response processing. Will be able to do that in a few days.

**Comment by staticlibs** [comment]
Confirming that this is not a bug, the problem happens when SQLServer Browser is enabled but TCP transport is NOT enabled for the chosen instance. Connection succeeds if TCP transport is enabled. 

So the behaviour is correct, just the error message could have been better than `Conversion error`. Unfortunately this error comes from inside the Tiberius DB lib so there is no easy way to change it. I've documented this error message in [this section in wiki](https://github.com/wiltondb/wiltondb/wiki/WiltonDB-Data-Transfer-GUI-tool#connect-to-mssql-instance-by-name).
