### ISSUE TITLE
Not able to create 'NT AUTHORITY\SYSTEM'

### ISSUE THREAD

**Issue by psrinivasa2** [wiltondb/wiltondb#58]
Hi Alex, 
I am trying to create 'NT AUTHORITY\SYSTEM' user for wiltonDB, but I could not create it, can you please help, Is there any syntax error?

![image](https://github.com/user-attachments/assets/8358619c-a7f9-4882-a663-59f15ec62adf)

![image](https://github.com/user-attachments/assets/19359dfb-ce2d-4ae7-a500-7470416931dc)

**Comment by staticlibs** [comment]
@psrinivasa2 

Indeed, domain names with spaces are not allowed by Babelfish due to Kerberos format. And Windows supplies `NT AUTHORITY` domain name for system users, like: `NT AUTHORITY\LOCAL SERVICE`.

Like with `@` symbols in user names, I've updated the SSPI handling logic to support `-` symbols in domain names instead of spaces. So the user for Local Service can be created like this:

```tsql
create login [NT-AUTHORITY\LOCAL SERVICE] from windows
```

This change is included in this [pre-release version 11.16.0.rc4](https://github.com/wiltondb/wiltondb/releases/tag/3.3-11-16-0-rc4), no other pending changes are included there. Please try with this version whether it will work for Local System user in your case.

**Comment by psrinivasa2** [comment]
Thanks Alex, I will check on Friday and let you know back

**Comment by psrinivasa2** [comment]
Hi Alex,
I have mailed you the testing observations, please check
