### ISSUE TITLE
RPM/DEB packages for LTS-12-16

### ISSUE THREAD

**Issue by Vonng** [wiltondb/wiltondb#81]
Glad to see the latest LTS release: https://github.com/wiltondb/wiltondb/releases/tag/3-lts-12-16-1

Wish to try the PostgreSQL 16 version of wiltondb on EL / Ubuntu, but the official repo seems still providing the old 15.4 version: https://download.copr.fedorainfracloud.org/results/wiltondb/wiltondb/epel-9-x86_64/07766767-postgresql/

Any plan on update the yum/apt repo? ;)

**Comment by staticlibs** [comment]
Hi! Yes, the update to Ubuntu and EL packages is currently being prepared. I will update the [news section](https://github.com/wiltondb/wiltondb?tab=readme-ov-file#news) when it is ready.

As with Windows, due to changes from [#2987](https://github.com/babelfish-for-postgresql/babelfish_extensions/issues/2987), there is no update path from `11.15`. Just, unlike Windows there is no automatic versioning of the DB cluster directory on Linux (have little control over it due to distro-specific placing). So the old DB cluster will need to be removed and `wiltondb-setup` is run again when `12.16` is installed.

**Comment by Vonng** [comment]
Thanks for your reply ;) .

BTW is there any plan or schedule on upgrading the underlying PostgreSQL to 16/17?

**Comment by staticlibs** [comment]
It is not possible to upgrade the major version of Postgres while keeping Babelfish major version the same. Babelfish 3.x can only be used with [postgresql_modified_for_babelfish](https://github.com/babelfish-for-postgresql/postgresql_modified_for_babelfish) 15.x. So WiltonDB 3 LTS remains on Postgres 15.

There are plans to create WiltonDB-latest build, that should follow upstream Babelfish closely. So WiltonDB 4.x build for Windows with Postgres 16 should be as close possible to the corresponding Aurora Babelfish 4.x and be compatible with it for replication, backups etc. Then WiltonDB 5.x with Postgres 17 and so on.

**Comment by staticlibs** [comment]
Closing as completed, please reopen if needed.
